[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcrypt"] # Optional: helps if bcrypt acts up

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
